# Generated by Django 2.2.2 on 2019-06-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
