# Generated by Django 2.2.2 on 2019-06-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('categoryId', models.ForeignKey(on_delete='CASCADE', to='category.Category')),
            ],
        ),
    ]
